### ISSUE TITLE
reverse coordinates

### ISSUE THREAD

**Issue by parallax688** [InquisitorJax/Wibci.CountryReverseGeocode#1]
Hi,
seems to me that the longitude and latitude are reversed somewhere, I take a point in the middle of the Switzerland country polygon,
`GeoLocation myloc = new GeoLocation { Latitude = 46.74, Longitude = 8.48 };`
should return Switzerland, but I get Somaliland instead,

if I reverse latitude and longitude:
`GeoLocation myloc = new GeoLocation { Latitude = 8.48, Longitude = 46.75 };`
I get the expected answer, Switzerland

**Comment by InquisitorJax** [comment]
Thanks - I'll take a look

**Comment by parallax688** [comment]
I think a search path would be that it is that the polygons in the json data are stored as Longitude, Latitude way,
then in the FindLocationInfo, you say 
locations.Add(new GeoLocation { Latitude = locationItem[0], Longitude = locationItem[1] });
and it is reverted

**Comment by InquisitorJax** [comment]
corrected and nuget package published (1.1.0)
Thanks for reporting.
