### ISSUE TITLE
Mixed up latitude and longitude

### ISSUE THREAD

**Issue by p4rnicke** [InquisitorJax/Wibci.CountryReverseGeocode#3]
I beleive you mixed the lat and long values.
For Hungary for example 47;18 gives Saudi Arabia, which is 18;47
This may answer the Russia problem also.

**Comment by InquisitorJax** [comment]
thanks for the heads up... if it was something as drastic as mixing lat and long - would that not mean the other countries would not work either?
perhaps the source country data has mixed lat / lon - will investigate - thx

**Comment by p4rnicke** [comment]
I agree with you.
Using the source there is no issue, it returns what it should.
I'm using the Nuget package, and with that I see this strange behaviour.
I really cannot explain it.

**Comment by InquisitorJax** [comment]
which version are you running? There was a lat lon fix in the latest 1.1 release

**Comment by p4rnicke** [comment]
This is what I wanted to write, that you fixed this in 1.1.
I just downloaded 1.1 from nuget, I've not used this package before, just started using today.
But I'm sure for some reason this package is not the same as it can be compiled now.

**Comment by p4rnicke** [comment]
The dll's file version shows 1.0
I don't know how nuget distrib works, but is it possible, that you uploaded an 1.0 version as 1.1?

**Comment by InquisitorJax** [comment]
anything's possible - I'll double check

**Comment by InquisitorJax** [comment]
looks like it was an old lib in the nuget package - uploading a new version now....

**Comment by InquisitorJax** [comment]
uploaded 1.2, and checked the output. Should be fixed now.
