### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jmwaldrip** [InquisitorJax/Wibci.CountryReverseGeocode#4]
I see that the original project is shipped under MIT. Is this shipped under MIT as well? If so, can you add the license file? Thank you!

**Comment by InquisitorJax** [comment]
added a license file. [commit](https://github.com/InquisitorJax/Wibci.CountryReverseGeocode/commit/8c9ab213ad1cad9fee4a93b63e7170478b02a8ae)

**Comment by jmwaldrip** [comment]
You're awesome! Thank you for such a quick response.
