### ISSUE TITLE
Wrong US State for (37.78595f, -122.4404f)

### ISSUE THREAD

**Issue by hk1ll3r** [InquisitorJax/Wibci.CountryReverseGeocode#5]
I came across this specific lat/long coordinate that returns null instead of California (it is in SF). 

Probably there are inaccuracies in the polygon data.

**Comment by InquisitorJax** [comment]
@hk1ll3r fixed in 2.0.1

**Comment by hk1ll3r** [comment]
Thanks for the fix. 
I'd like to be able to do similar fixes if I face them in the future. What tool do you use for getting the geometry data? Is there a map website that lets you define polygons and export their vertex lang/lat data?

PS typo in the new california test case. The variable for california geolocation is named alabama.

**Comment by InquisitorJax** [comment]
I included some data source links in the resources.txt file, as well as more accurate state data in the resources folder (although I only updated California).

The original polygon data was just copied from the original javascript project linked in the readme.
